### ISSUE TITLE
Add libluv to COPR

### ISSUE THREAD

**Issue by agriffis** [agriffis/neovim#1]
Nightly COPR builds are failing since https://github.com/neovim/neovim/commit/c83926cd0aa5720e88e84fa3fae3c0e689cca3ef#diff-af3b638bc2a3e6c650974192a53c7291

We need to add libluv, see https://github.com/luvit/luv

**Comment by hkupty** [comment]
Is there a way to add https://apps.fedoraproject.org/packages/libuv as a dependency? It's been a long time w/o a release and fedora's version is quite old.

**Comment by agriffis** [comment]
@hkupty It isn't libuv that we need, it's libluv, see https://github.com/luvit/luv

I started working on it but realized I was going about it the wrong way.  libluv needs to be installed as both a library and a lua module. You can see my work in progress at https://github.com/agriffis/luv/commits/copr

I'll see if I can get it running again soon

**Comment by hkupty** [comment]
Sorry for the confusion, but nonetheless thanks for the effort. :)

**Comment by agriffis** [comment]
Fixed!
