### ISSUE TITLE
Fedora 34 repository gone missing

### ISSUE THREAD

**Issue by dietrichm** [agriffis/neovim#13]
### Neovim version (nvim -v)

n/a

### Vim (not Nvim) behaves the same?

n/a

### Operating system/version

n/a

### Terminal name/version

n/a

### $TERM environment variable

n/a

### Installation

COPR repo

### How to reproduce the issue

dnf copr enable agriffis/neovim-nightly -y

Enabling a Copr repository. Please note that this repository is not part
of the main distribution, and quality may vary.

The Fedora Project does not exercise any power over the contents of
this repository beyond the rules outlined in the Copr FAQ at
<https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr>,
and packages are not held to any quality or security level.

Please do not file bug reports about these packages in Fedora
Bugzilla. In case of problems, contact the owner of this repository.
Error: This repository does not have any builds yet so you cannot enable it now.

### Expected behavior

Fedora 34 repository is enabled.

### Actual behavior

Repository is not available as per `dnf` and https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/.

**Comment by agriffis** [comment]
The repo is back. Seems to have been a COPR glitch.

However the builds are [broken for F34](https://download.copr.fedorainfracloud.org/results/agriffis/neovim-nightly/fedora-34-x86_64/03223919-neovim/builder-live.log.gz) so I've disabled them. I don't put a high priority on keeping nightly builds alive for non-current releases.

I don't know how long COPR will keep the repo when the builds are disabled for that release. If you're unable to upgrade to F35 then you might want to grab the rpms for future installs.
