### ISSUE TITLE
NeoVim freezes on :q or ^O

### ISSUE THREAD

**Issue by mgrabovsky** [agriffis/neovim#14]
### Neovim version (nvim -v)

v0.7.0-dev+1049-g3b4bf8871

### Vim (not Nvim) behaves the same?

no, vim-enhanced-8.2.4314-1.fc35.x86_64

### Operating system/version

Fedora 35

### Terminal name/version

gnome-terminal-3.42.2-1.fc35.x86_64

### $TERM environment variable

screen-256color

### Installation

Copr agriffis/neovim-nightly

### How to reproduce the issue

    nvim -u NONE
    :q or C-o

### Expected behavior

NeoVim clears the screen, exits and returns control to the shell.

### Actual behavior

NeoVim freezes and doesn't respond to `SIGTERM`.

**Comment by mgrabovsky** [comment]
Did a `dnf downgrade` to 1042-g01b748f28, same problem.

**Comment by mgrabovsky** [comment]
What's interesting is that gstack hangs as well when trying to attach to the process…

**Comment by agriffis** [comment]
Hi! This repo is only for nightly builds in COPR. I can't help with neovim bugs here.

For general Neovim bugs, see https://github.com/neovim/neovim/issues

For Neovim bugs in Fedora, see https://bugzilla.redhat.com/

**Comment by agriffis** [comment]
(Also, I'm running the COPR builds on F35 and definitely not seeing the problem you mentioned)
