### ISSUE TITLE
Copr build failing

### ISSUE THREAD

**Issue by peteryates** [agriffis/neovim#15]
Apologies if this isn't the right place to raise issues with the Copr build, but it appears it's been failing for a few days.

Here's the relevant bit of the error in [the build log](https://download.copr.fedorainfracloud.org/results/agriffis/neovim-nightly/fedora-35-x86_64/03580192-neovim/build.log.gz):

```
error: File not found: /builddir/build/BUILDROOT/neovim-0.7.0~dev.1156.ge38354334-732.fc35.x86_64/usr/share/licenses/neovim/LICENSE
RPM build errors:
    File not found: /builddir/build/BUILDROOT/neovim-0.7.0~dev.1156.ge38354334-732.fc35.x86_64/usr/share/licenses/neovim/LICENSE
```

I believe it's caused by [this commit](https://github.com/neovim/neovim/commit/087aad3dcd3439bb87832356067e0a9e26eca510) which (for some reason) renames `LICENCE` to `LICENCE.txt`

**Comment by agriffis** [comment]
Thanks, fixed now!

**Comment by agriffis** [comment]
(And thanks for tracking down the problem, that saved me some time.)
