### ISSUE TITLE
Copr build failing

### ISSUE THREAD

**Issue by zenofile** [agriffis/neovim#16]
### Feature description

The copr builds are failing for two weeks with this error:

```log
+ echo 'Patch #0 (neovim-libvterm-0-2-support.patch):'
Patch #0 (neovim-libvterm-0-2-support.patch):
+ /usr/bin/patch --no-backup-if-mismatch -f -p1 --fuzz=0
patching file src/nvim/terminal.c
Hunk #1 FAILED at 844.
1 out of 1 hunk FAILED -- saving rejects to file src/nvim/terminal.c.rej
error: Bad exit status from /var/tmp/rpm-tmp.3kMOh0 (%prep)
```

https://download.copr.fedorainfracloud.org/results/agriffis/neovim-nightly/fedora-36-x86_64/04869599-neovim/builder-live.log.gz

Apologies for the “Feature request” issue, but the “Bug Report” one has a nonsensical template for this repository.

**Comment by agriffis** [comment]
Thanks! I fixed that and it builds now for rawhide. The others still depend on libvterm 0.3 that is in the updates-testing repos, so I suppose they'll start building when that becomes available.

**Comment by zenofile** [comment]
I tested manually building it on Fedora 36 with libvterm-devel 0.3-1 and your patch applied, and it seems to work fine, thank you.

**Comment by agriffis** [comment]
Builds all working again as of a couple days ago https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/builds/
