### ISSUE TITLE
Builds have been failing since bf0ddb40af609189aaad96df92a8759b6c645338

### ISSUE THREAD

**Issue by mbaldessari** [agriffis/neovim#17]
### Problem

Seems the regression happened between: 
bb7ecaaaeedcf99da41d126fdb346f03b6b0b96e - https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/build/5594648/
bf0ddb40af609189aaad96df92a8759b6c645338 - https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/build/5597375/

The error being:
/expressions.c.o CMakeFiles/nvim.dir/viml/parser/parser.c.o CMakeFiles/nvim.dir/window.c.o CMakeFiles/nvim.dir/__/cjson/fpconv.c.o CMakeFiles/nvim.dir/__/cjson/lua_cjson.c.o CMakeFiles/nvim.dir/__/cjson/strbuf.c.o CMakeFiles/nvim.dir/__/mpack/conv.c.o CMakeFiles/nvim.dir/__/mpack/lmpack.c.o CMakeFiles/nvim.dir/__/mpack/mpack_core.c.o CMakeFiles/nvim.dir/__/mpack/object.c.o CMakeFiles/nvim.dir/__/mpack/rpc.c.o CMakeFiles/nvim.dir/__/xdiff/xdiffi.c.o CMakeFiles/nvim.dir/__/xdiff/xemit.c.o CMakeFiles/nvim.dir/__/xdiff/xhistogram.c.o CMakeFiles/nvim.dir/__/xdiff/xpatience.c.o CMakeFiles/nvim.dir/__/xdiff/xprepare.c.o CMakeFiles/nvim.dir/__/xdiff/xutils.c.o -o ../../bin/nvim   -L/usr/lib64/luajit/2.1  -Wl,-rpath,/usr/lib64/luajit/2.1: -Wl,--no-undefined -lluv /usr/lib64/libtermkey.so /usr/lib64/libvterm.so /usr/lib64/libmsgpackc.so /usr/lib64/libtree-sitter.so /usr/lib64/libunibilium.so /usr/lib64/libluajit-5.1.so -fstack-protector-strong -lm -lutil /usr/lib64/libuv.so -ldl -lrt 
/usr/bin/ld: cannot find -lluv: No such file or directory

From a quick git grep around luv:
```
git lg -i --no-merges --grep luv bb7ecaaaeedcf99da41d126fdb346f03b6b0b96e..bf0ddb40af609189aaad96df92a8759b6c645338
da0c66bcd - (2023-03-05 21:13:28 +0100)  build: remove workaround for incorrectly packaged libluv <dundargoc>
```

Seems da0c66bcd has potential to be the culprit here?

### Steps to reproduce

--

### Expected behavior

--

### Neovim version (nvim -v)

 	0.9.0~dev.1234.g5a38e951e-500 

### Vim (not Nvim) behaves the same?

--

### Operating system/version

--

### Terminal name/version

--

### $TERM environment variable

--

### Installation

--

**Comment by mbaldessari** [comment]
I can confirm that backing out https://github.com/agriffis/neovim/commit/da0c66bcddbe4e6ebc72357c9f6c5de75e176744 fixes the build for me

**Comment by agriffis** [comment]
Thanks for tracking that down! Just pushed to COPR, should be building soon.

**Comment by mbaldessari** [comment]
Thank *you* @agriffis !
