### ISSUE TITLE
Error when running latest from copr

### ISSUE THREAD

**Issue by mr** [agriffis/neovim#2]
- `nvim --version`: current
- Operating system/version: fedora 30
- Terminal name/version: gnome-terminal
- `$TERM`: tmux-256color

### Steps to reproduce using `nvim -u NORC`

```
nvim -u NORC
# Alternative for shell-related problems:
# env -i TERM=ansi-256color "$(which nvim)"
```

### Actual behaviour
```
nvim: error while loading shared libraries: /usr/lib64/lua/5.1/luv.so: cannot open shared object file: No such file or directory
```
### Expected behaviour
Doesn't crash

**Comment by agriffis** [comment]
Thanks for the report. Was missing a requirement. Try now?  `dnf upgrade --refresh neovim`
