### ISSUE TITLE
Builds failing since 6d829a6c583f97155cf507f59d486cf6c52c95af

### ISSUE THREAD

**Issue by stsewd** [agriffis/neovim#20]
### Problem

Hi there, thanks again for maintaining this package!

Builds have been failing since this commit https://github.com/agriffis/neovim/commit/6d829a6c583f97155cf507f59d486cf6c52c95af

https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/package/neovim/

Maybe the problem comes from this commit https://github.com/agriffis/neovim/commit/0a3645a72307afa563683a6e06c544810e0b65eb? Kind of similar to https://github.com/agriffis/neovim/issues/17.
I think there is an error while applying this patch https://github.com/agriffis/neovim/blob/copr/neovim-restore-libluv-workaround.patch.

### Steps to reproduce

...

### Expected behavior

..

### Neovim version (nvim -v)

...

### Vim (not Nvim) behaves the same?

...

### Operating system/version

...

### Terminal name/version

...

### $TERM environment variable

...

### Installation

...

**Comment by agriffis** [comment]
fixed by 3963ff128
