### ISSUE TITLE
Requires lua5.1-lpeg to be manually installed

### ISSUE THREAD

**Issue by ErikReider** [agriffis/neovim#21]
### Problem

Neovim won't open until `lua5.1-lpeg` is manually installed, should be a required package

### Steps to reproduce

Run Neovim without the missing dep installed. Should output `nvim: error while loading shared libraries: /usr/lib64/lua/5.1/lpeg.so: cannot open shared object file: No such file or directory`

### Expected behavior

Opens as usual

### Neovim version (nvim -v)

NVIM v0.10.0-dev+361-ge3e6fadfd

### Vim (not Nvim) behaves the same?

No

### Operating system/version

Fedora 38

### Terminal name/version

Kitty

### $TERM environment variable

xterm-256color

### Installation

COPR

**Comment by agriffis** [comment]
and 4aad1d3e0
