### ISSUE TITLE
tree-sitter highlighting is broken on the Fedora 38 COPR version of neovim

### ISSUE THREAD

**Issue by bugnano** [agriffis/neovim#22]
### Problem

I'm using the COPR version of neovim on Fedora 38 x86_64.
Since a few days (I don't know when this problem started), tree-sitter highlighting stopped working, and now every file I open looks like plain text without any colours.

### Steps to reproduce

- Use neovim from the COPR on Fedora 38
- Add the `nvim-treesitter/nvim-treesitter` plugin, configured to use all the parsers and highlighting enabled
- Add the `nvim-treesitter/playground` plugin, in order to be able to use `:TSHighlightCapturesUnderCursor`
- Use a colorscheme that is compatible with tree-sitter
- Open a file that should be highlighted (any LUA file for example)

### Expected behavior

I expect the file to be correctly highlighted, and if I run `:TSHighlightCapturesUnderCursor`, I expect to see something like:
```
 # Treesitter
 * @variable
 * @function.call
 ```

Instead, if I run `:TSHighlightCapturesUnderCursor`, I see:

```
* No highlight groups found
```

Note that with the exact same config, if I run the nightly appimage from the neovim GitHub, everything works perfectly.

### Neovim version (nvim -v)

NVIM v0.10.0-dev+766-gef44e5972

### Vim (not Nvim) behaves the same?

not applicable to Vim

### Operating system/version

Fedora 38 x86_64

### Terminal name/version

GNOME Terminal 3.48.1

### $TERM environment variable

xterm-256color

### Installation

COPR

**Comment by agriffis** [comment]
Hi! Thanks for the report.

I'm unable to track down the problem at the moment. If you have a chance, could you try some of the recent daily builds to find when it stopped working? Maybe something changed upstream that we need to incorporate into the COPR build.

**Comment by stsewd** [comment]
I found this as well, solved it by downgrading lib-treesitter, but looks like this will be fixed in the next nightly build https://github.com/neovim/neovim/pull/24607.

**Comment by bugnano** [comment]
The bug has been fixed in the latest nightly build, so I think that this issue can be safely closed
