### ISSUE TITLE
Build broken by libvterm 0.3.3 requirement

### ISSUE THREAD

**Issue by agriffis** [agriffis/neovim#24]
Fedora only has 0.3 but neovim recently updated the dep to 0.3.3, see https://github.com/neovim/neovim/pull/25777

**Comment by agriffis** [comment]
Fedora rpm is on 0.9.4 which doesn't have the problem (yet) https://src.fedoraproject.org/rpms/neovim

**Comment by agriffis** [comment]
Options at this point:

1. Help Fedora update to libvterm 0.3.3
2. Carry libvterm 0.3.3 in COPR (bad idea)
3. Relax dep in our build, depending on severity of issues in older libvterm

**Comment by Kleidukos** [comment]
I would encourage that we go with 1 first. :)

**Comment by agriffis** [comment]
@Kleidukos Agreed. I can't work on it at the moment, though. If you're able to contribute, please file a bugzilla with Fedora for the update, and keep this issue posted with progress.

**Comment by Kleidukos** [comment]
I can observe that Fedora 39 (recently released) ships 0.3.3 https://src.fedoraproject.org/rpms/libvterm. One solution is to push for 38 to have 0.3.3 used in place of 0.3.2 (no idea if this will be accepted) or to only produce builds for Fedora 39+ from now on (more realistic even though I don't particularly appreciate this outcome)

**Comment by agriffis** [comment]
It's up to you, really depends on how much upstreaming work you want to do.

F39+ is fine with me. These are nightly builds after all.

**Comment by Kleidukos** [comment]
Indeed. Let's with F39+ then! Is there a file to change in this repo that I can tweak to obtain this?

**Comment by agriffis** [comment]
I just made that change in the COPR web interface. We were already only building F38+

Build is running now, see https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/build/6613162/

Not sure if there's still a problem we need to handle in the spec though

**Comment by agriffis** [comment]
```
No matching package to install: 'pkgconfig(vterm) >= 0.3.3'
```

I think you mistook `0.3-3` for `0.3.3` in Fedora upstream?

**Comment by Kleidukos** [comment]
ughh indeed, one small character difference. I'll open a ticket

**Comment by Kleidukos** [comment]
Here we go: https://bugzilla.redhat.com/show_bug.cgi?id=2248743

**Comment by agriffis** [comment]
I made a bug report against libvterm to update the home page with the latest tarball

https://bugs.launchpad.net/libvterm/+bug/2043041

**Comment by mochaaP** [comment]
![image](https://github.com/agriffis/neovim/assets/21154023/27a79fee-7234-41b7-a119-c2a747928bbe)

Resolved: <https://www.leonerd.org.uk/code/libvterm/libvterm-0.3.3.tar.gz>

**Comment by agriffis** [comment]
Great, thanks!

I had some trouble with src.fedoraproject.org credentials and got distracted by work, but I'll try to get this fixed soon.

**Comment by mochaaP** [comment]
@agriffis Fedora package done in <https://src.fedoraproject.org/rpms/libvterm/pull-request/4>

**Comment by mochaaP** [comment]
Merged to rawhide.

**Comment by agriffis** [comment]
Awesome, thanks! How about f39?

**Comment by mochaaP** [comment]
f39: <https://src.fedoraproject.org/rpms/libvterm/pull-request/5>

**Comment by mochaaP** [comment]
f40 update submitted: <https://bodhi.fedoraproject.org/updates/FEDORA-2023-ee7f7fd789>
will submit f39 as soon as it gets merged.

**Comment by agriffis** [comment]
FYI I'm still getting `No matching package to install: 'pkgconfig(vterm) >= 0.3.3'`

Possibly COPR just isn't up to date yet.  See https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/build/6680468/

**Comment by mochaaP** [comment]
> FYI I'm still getting `No matching package to install: 'pkgconfig(vterm) >= 0.3.3'`
> 
> Possibly COPR just isn't up to date yet. See [copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/build/6680468](https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/build/6680468/)

Please wait for the package to sync to all the mirrors, might take half a day or longer. :)
It's also recommended to remove the outdated libvterm package in Copr.

**Comment by mochaaP** [comment]
Test Neovim builds live at <https://copr.fedorainfracloud.org/coprs/mochaa/neovim-nightly/build/6682806/> (testing purposes only! will pollute your system installation of libvterm since it's shipped in the Copr)

**Comment by mochaaP** [comment]
Upvotes required to bring this to F39 stable: <https://bodhi.fedoraproject.org/updates/FEDORA-2023-e9831e76f8>

**Comment by agriffis** [comment]
Rawhide builds in my COPR are working now. F39 waiting on the upvotes.

https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/build/6684665/

**Comment by agriffis** [comment]
Last night's build passed on F39 and Rawhide. Thank you everybody, especially @mochaaP, for your help getting this unstuck!
