### ISSUE TITLE
error: nvim: undefined symbol: ts_query_cursor_set_max_start_depth

### ISSUE THREAD

**Issue by rickyrsyah** [agriffis/neovim#25]
### Problem

i got message when run `nvim` command, e.g `nvim --version`
> nvim: symbol lookup error: nvim: undefined symbol: ts_query_cursor_set_max_start_depth

### Steps to reproduce

```bash
sudo dnf install neovim-0.10.0~dev.1825.gd65c6a0ba-500.fc39 -y
nvim
```

### Expected behavior

open nvim normally

### Neovim version (nvim -v)

nvim: symbol lookup error: nvim: undefined symbol: ts_query_cursor_set_max_start_depth

### Vim (not Nvim) behaves the same?

no, VIM - Vi IMproved 9.0

### Operating system/version

Fedora Linux 39 (Container Image)

### Terminal name/version

foot 1.16.1

### $TERM environment variable

foot

### Installation

copr:copr.fedorainfracloud.org:agriffis:neovim-nightly

**Comment by rickyrsyah** [comment]
i fix this error with run
`sudo dnf upgrade libtree-sitter`
it install `libtree-sitter-0.20.8.0.git.4257.2cbfcbc3-1.fc39` from your COPR
before libtree-sitter on my system is `libtree-sitter-0.20.8-2.fc39`

**Comment by agriffis** [comment]
oh, that's interesting, thanks. It seems like tree-sitter needs to make a versioned release for this.

I think for now I'll wait to see if more people stumble on this before taking special measures (modifying the neovim spec to force the COPR build of libtree-sitter). Hopefully the upstream versioning will sort things out.

Thank you for following up.
