### ISSUE TITLE
Builds broken due to missing BACKERS.md

### ISSUE THREAD

**Issue by mbaldessari** [agriffis/neovim#26]
### Problem

Upstream renamed BACKERS.md to runtime/doc/backers.txt via 31d7007bf745d3f03902b27c2124d473ec2f8906. Jobs are now failing with 
```
RPM build errors:
    File not found: /builddir/build/BUILDROOT/neovim-0.10.0~dev.2296.gcca8a78ea-500.fc39.x86_64/usr/share/doc/neovim/BACKERS.md
```
Can we drop that file from the `%doc` section?

### Steps to reproduce

https://download.copr.fedorainfracloud.org/results/agriffis/neovim-nightly/fedora-39-x86_64/06995870-neovim/builder-live.log.gz

### Expected behavior

Working build

### Neovim version (nvim -v)

neovim-0.10.0~dev.1974.g714b07519-500.fc39.x86_64

### Vim (not Nvim) behaves the same?

no

### Operating system/version

Fedora 39

### Terminal name/version

alacritty

### $TERM environment variable

xterm-256color

### Installation

copr

**Comment by agriffis** [comment]
Thanks for the heads up
