### ISSUE TITLE
pgp keys seem to be outdated

### ISSUE THREAD

**Issue by Lazerbeak12345** [agriffis/neovim#28]
### Problem

as installed though this copr https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/ the keys were getting rejected by fedora

See also: https://superuser.com/questions/1785327/unable-to-update-with-dnf-because-of-a-gpg-check-failed

### Steps to reproduce

attempt to update system with `sudo dnf update` after having had neovim fully functioning before

### Expected behavior

dnf can update neovim.

### Neovim version (nvim -v)

unsure/ N/A

### Vim (not Nvim) behaves the same?

N/A

### Operating system/version

Fedora 39

### Terminal name/version

N/A

### $TERM environment variable

N/A

### Installation

COPR

**Comment by agriffis** [comment]
Dup of #27 I think!
