### ISSUE TITLE
Not pulling lasted build for fedora 33

### ISSUE THREAD

**Issue by boydkelly** [agriffis/neovim#3]
Hi,

I am noticing this weird behaviour in my Fedora 33 toolbox.   I have activated the nightly build copr but the package installeed is from way back in time August 22.   I have nuked the repo files and retried but consistently this package is installed.   Is this a copr or config issue?

⬢[root@toolbox yum.repos.d]# dnf info neovim
Last metadata expiration check: 0:06:08 ago on Wed Nov  4 22:15:20 2020.
Installed Packages
Name         : neovim
Version      : 0.4.4.0.git.16218.161cdba1e
Release      : 1.fc33
Architecture : x86_64
Size         : 21 M
Source       : neovim-0.4.4.0.git.16218.161cdba1e-1.fc33.src.rpm

This is the build from August 22.
https://download.copr.fedorainfracloud.org/results/agriffis/neovim-nightly/fedora-33-x86_64/01624554-neovim/

⬢[root@toolbox yum.repos.d]# cat /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:agriffis:neovim-nightly.repo
[copr:copr.fedorainfracloud.org:agriffis:neovim-nightly]
name=Copr repo for neovim-nightly owned by agriffis
baseurl=https://download.copr.fedorainfracloud.org/results/agriffis/neovim-nightly/fedora-$releasever-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://download.copr.fedorainfracloud.org/results/agriffis/neovim-nightly/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
⬢[root@toolbox yum.repos.d]# 

⬢[root@toolbox yum.repos.d]# cat /etc/fedora-release 
Fedora release 33 (Thirty Three)
⬢[root@toolbox yum.repos.d]#

**Comment by agriffis** [comment]
Thanks, looks like an old build had a newer effective version number than the current one.

I just removed the old build from COPR, so you should get the latest when you install. You won't get it if you upgrade, though, so if you already have it installed, you'll need to `sudo dnf remove -y neovim && sudo dnf install -y neovim`

This will sort itself out when there's a new versioned release of neovim...

**Comment by agriffis** [comment]
Oh, you might need to use `dnf install --refresh -y neovim` to make sure you have the latest repo file
