### ISSUE TITLE
Builds are failing

### ISSUE THREAD

**Issue by jglueckstein** [agriffis/neovim#30]
### Problem

[COPR build log](https://download.copr.fedorainfracloud.org/results/agriffis/neovim-nightly/fedora-40-x86_64/07716472-neovim/builder-live.log.gz) shows:

> CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find UTF8proc (missing: UTF8PROC_LIBRARY UTF8PROC_INCLUDE_DIR)
> Call Stack (most recent call first):
>   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
>   cmake/FindUTF8proc.cmake:3 (find_package_handle_standard_args)
>   src/nvim/CMakeLists.txt:38 (find_package)

This is possibly related to recent neovim commit [build: add utf8proc as dependency](https://github.com/neovim/neovim/commit/32e16cb0b6b046ba45d3e14c0fdb0383ad8bee1e)

### Steps to reproduce

Go to COPR [project page](https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/).
Realize builds are failing.

### Expected behavior

Builds not failing.

### Neovim version (nvim -v)

last successful build 0.11.0~dev.315.g46187117c-1

### Vim (not Nvim) behaves the same?

no

### Operating system/version

fedora 40

### Terminal name/version

any

### $TERM environment variable

NA

### Installation

COPR

**Comment by agriffis** [comment]
Thanks, working on it

**Comment by agriffis** [comment]
Fixed, thanks for the heads up!
