### ISSUE TITLE
Builds are failing

### ISSUE THREAD

**Issue by jglueckstein** [agriffis/neovim#31]
### Problem

Builds have been failing since August 31st.  I examined the build log [here](https://download.copr.fedorainfracloud.org/results/agriffis/neovim-nightly/fedora-39-aarch64/07967612-neovim/builder-live.log.gz).  It looks like neovim changed their build process in this recent [commit](https://github.com/neovim/neovim/commit/26be6446e5ea1c5b22c50bfd9a0e5aa85927aff9).

### Steps to reproduce

See [copr](https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/)

### Expected behavior

Builds succeeding.

### Neovim version (nvim -v)

Last successful build: NVIM v0.11.0-dev+684-g53af02adb

### Vim (not Nvim) behaves the same?

no

### Operating system/version

fedora 40

### Terminal name/version

any

### $TERM environment variable

NA

### Installation

COPR

**Comment by jglueckstein** [comment]
Would it help if we politely asked utf8proc to bump their version number?

**Comment by agriffis** [comment]
That seems like a good place to start.

**Comment by agriffis** [comment]
I added utf8proc to the nightly copr builds. Neovim builds are unstuck.

https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/builds/

**Comment by agriffis** [comment]
You might need to

```
sudo dnf upgrade --refresh --best --allowerasing
```

if you have something (like subversion) that depends on the older utf8proc. Just don't remove something you care about!

**Comment by jglueckstein** [comment]
Thank you!

For the record, I had to remove both subversion and julia due to dependence on the older utf8proc.
