### ISSUE TITLE
Please branch for EPEL 9

### ISSUE THREAD

**Issue by nisbet-hubbard** [agriffis/neovim#32]
### Problem

Repo only builds for Fedora.

### Expected behavior

Could you please also build the nightly version for the `epel-9-x86_64` chroot on COPR?

**Comment by agriffis** [comment]
This isn't trivial as it's missing deps. I'm sorry, but I probably won't invest time into this personally.

If you want to get it working, the first step would be building `https://github.com/agriffis/tree-sitter/tree/copr` (specifically that branch) locally on your EPEL system with rpkg

**Comment by agriffis** [comment]
@nisbet-hubbard I just wanted to follow up and say that the upstream neovim nightly builds probably work fine on EPEL, for example the appimage. https://github.com/neovim/neovim/releases
