### ISSUE TITLE
Latest two builds failed

### ISSUE THREAD

**Issue by stsewd** [agriffis/neovim#4]
Thanks for maintaining this package for fedora! I noticed the last two builds failed

https://copr.fedorainfracloud.org/coprs/agriffis/neovim-nightly/builds/

Looks related to neovim not shipping the treesitter dependency in the code base https://github.com/neovim/neovim/pull/1293

**Comment by hargoniX** [comment]
The builds are still failing and it appears that https://github.com/neovim/neovim/issues/13210 this bug is not yet fixed in the currently built version which makes using nvim-lsp with this COPR repo pretty annoying :( Would be very cool if this was fixed!

**Comment by agriffis** [comment]
Thanks for the heads up. I expect to fix this in the same way as Homebrew, see https://github.com/Homebrew/homebrew-core/pull/64015/files

**Comment by agriffis** [comment]
Should be fixed now. `sudo dnf upgrade neovim --refresh`
