### ISSUE TITLE
Add support for pre-release versions

### ISSUE THREAD

**Issue by likern** [agriffis/neovim#6]
Hello! Thank you for your repository.

I'm trying to play around with latest NeoVim builds, such as NVIM v0.5.0-dev+1075-g02a3c4179. Not sure it's tye problem, but installed AppImage doesn't work with lua extensions.

Could you add to your script building and publishing pre-release latest builds, such as NVIM v0.5.0-dev+1075-g02a3c4179?

**Comment by likern** [comment]
Looks like they are already nightly builds. But, by some reason, do not use current `0.5.0` version prefix.

**Comment by agriffis** [comment]
Hi! I just reopened #5 of which this is effectively a dup. There's some conversation there that explains the versioning and potential changes.
