### ISSUE TITLE
aarch64

### ISSUE THREAD

**Issue by boydkelly** [agriffis/neovim#7]
Hi,
Just curious, have you tried or is there any reason that neovim-nightly will or won't compile for arm?
thx for this awesome copr!

**Comment by agriffis** [comment]
It doesn't seem to build. Here's a failure with luajit

https://download.copr.fedorainfracloud.org/results/agriffis/neovim-nightly/fedora-rawhide-aarch64/01995821-neovim/builder-live.log

and here's a failure with lua-5.4

https://download.copr.fedorainfracloud.org/results/agriffis/neovim-nightly/fedora-rawhide-aarch64/01995820-neovim/builder-live.log.gz

Please feel free to investigate, first install the deps:

```
sudo dnf copr enable agriffis/neovim-nightly
sudo dnf install rpm-build rpkg tree-sitter-devel
sudo dnf builddep neovim
```

then clone this repo, and

```
git checkout copr
rpkg local
```

Let me know if you figure it out...
